### PR TITLE
Add rbac and psp

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards [#2296](https://github.com/giantswarm/giantswarm/issues/2296)

### CODE REVIEW

**Comment by calvix** [comment]
yeah good point, we might remove it quite soon

**Comment by pipo02mix** [comment]
Yes but if RBAC is enabled in the host cluster then this component will need a rule, right?

**Comment by r7vme** [comment]
Yes.

**Comment by calvix** [comment]
i think we can close this, new clusters with RBAC will be running on new calico so there wont be state where we will have RBAC + calico-node-controller

**Comment by r7vme** [comment]
let's close this. calico-node-controller is not used anymore.

**Pull request closed without merging**
